CREATE TABLE ZIKA_IMOBILIARIA.ENDERECO (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CEP VARCHAR(40) NOT NULL,
    LOGRADOURO VARCHAR(40) NOT NULL,
    BAIRRO VARCHAR(40) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    FLAG_ALOCAVEL BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = INNODB;

CREATE TABLE CLIENTE(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    ID_ENDERECO INT(11) NOT NULL,
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(40),
    SEXO VARCHAR(9),
    ESTADO_CIVIL VARCHAR(10),
    PROFISSAO VARCHAR(40),
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    PRIMARY KEY(CPF),
    FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE FUNCIONARIO(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    ID_ENDERECO INT(11) NOT NULL,
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(40),
    SEXO VARCHAR(9),
    ESTADO_CIVIL VARCHAR(10),
    PROFISSAO VARCHAR(40),
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    CARGO VARCHAR(40),
    SALARIO DOUBLE(7, 2),
    PRIMARY KEY(CPF),
    FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE IMOVEL(
    COD INT(30) NOT NULL AUTO_INCREMENT,
    DONO_CPF VARCHAR(11),
    PROPOSITO VARCHAR(8),
    ID_ENDERECO INT(11) NOT NULL,
    TIPO VARCHAR(11),
    VALOR FLOAT(10,2),
    N_QUARTOS INT(2),
    N_SUITES INT(2),
    DESCRICAO VARCHAR(200),
    AREA_TERENO FLOAT(5,2) NULL,
    TEM_PISCINA BOOLEAN,
    NUM_AP INT(3) NULL,
    ANDAR INT(2) NULL,
    VALOR_CONDOMINIO FLOAT(4,2) NULL,
    PRIMARY KEY (COD),
    FOREIGN KEY(DONO_CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE IMAGENS(
    IMOVEL_COD INT (30),
    CAMINHO_IMG VARCHAR(40),
    FOREIGN KEY(IMOVEL_COD) REFERENCES IMOVEL(COD)
);


-- INSERTS

INSERT INTO `CLIENTE` (`CPF`, `NOME`, `ID_ENDERECO`, `TELEFONE`, `EMAIL`, `SEXO`, `ESTADO_CIVIL`, `PROFISSAO`, `USUARIO`, `SENHA`) VALUES
('32132', 'Gustavo', 1, '621', 'gg@gmil.com', 'M', 'Single', 'Cobolzeira', 'gnpc', '123');


INSERT INTO `ENDERECO` (`ID`, `CEP`, `LOGRADOURO`, `BAIRRO`, `CIDADE`, `FLAG_ALOCAVEL`) VALUES
(1, '231321', 'Lugar', 'bairro', 'cidade', 1);

INSERT INTO `FUNCIONARIO` (`CPF`, `NOME`, `ID_ENDERECO`, `TELEFONE`, `EMAIL`, `SEXO`, `ESTADO_CIVIL`, `PROFISSAO`, `USUARIO`, `SENHA`, `CARGO`, `SALARIO`) VALUES
('191', 'Carlos Arturo', 1, '231', 'carlos@car.com', 'M', 'Solteiro', 'Macho', 'user', '123', 'brabo', 10.00);

INSERT INTO `IMAGENS` (`IMOVEL_COD`, `CAMINHO_IMG`) VALUES
(1, '/seu/coracao');

INSERT INTO `IMOVEL` (`COD`, `DONO_CPF`, `PROPOSITO`, `ID_ENDERECO`, `TIPO`, `VALOR`, `N_QUARTOS`, `N_SUITES`, `DESCRICAO`, `AREA_TERENO`, `TEM_PISCINA`, `NUM_AP`, `ANDAR`, `VALOR_CONDOMINIO`) VALUES
(1, '32132', 'nada', 1, NULL, 100.22, 5, 2, 'asdfasf', 10.20, 1, 5, 2, NULL);